// src/components/Dashboard.vue
<script setup>
import { ref, computed } from 'vue'
import Header from './Header.vue'
import Timeline from './Timeline.vue'
import { TEAMS, generateShifts } from '@/data/mockData'

const selectedDate = ref(new Date())
const selectedTimezone = ref(Intl.DateTimeFormat().resolvedOptions().timeZone)

const shifts = computed(() => generateShifts(selectedDate.value))
</script>

<template>
  <div class="flex flex-col h-full bg-slate-50 text-slate-900 font-sans">
    <Header v-model:selected-date="selectedDate" v-model:selected-timezone="selectedTimezone" />
    <div class="flex-1 overflow-hidden relative">
      <Timeline
        :selected-date="selectedDate"
        :selected-timezone="selectedTimezone"
        :teams="TEAMS"
        :shifts="shifts"
      />
    </div>
  </div>
</template>

// figma-design/src/app/components/Dashboard.tsx
import { useState } from 'react';
import { Header } from './Header';
import { Timeline } from './Timeline';
import { TEAMS, generateShifts } from '../data/mockData';

export default function Dashboard() {
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [selectedTimezone, setSelectedTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone);

  // Shifts are generated based on the selected date to simulate fetching for that day
  const shifts = generateShifts(selectedDate);

  return (
    <div className="flex flex-col h-full bg-slate-50 text-slate-900 font-sans">
      <Header 
        selectedDate={selectedDate} 
        onDateChange={setSelectedDate}
        selectedTimezone={selectedTimezone}
        onTimezoneChange={setSelectedTimezone}
      />
      <div className="flex-1 overflow-hidden relative">
         <Timeline 
            selectedDate={selectedDate}
            selectedTimezone={selectedTimezone}
            teams={TEAMS}
            shifts={shifts}
         />
      </div>
    </div>
  );
}
